// Imagery for the location landing pages.
//
// All five files are WebP generated by scripts/optimise-images.js from sources
// that ranged from 425 KB to 1.9 MB. Each is served at the width it is actually
// displayed, with a 2x for retina.

import marketing from '../assets/lp/lp-marketing.webp';
import marketing2x from '../assets/lp/lp-marketing@2x.webp';
import media from '../assets/lp/lp-media.webp';
import media2x from '../assets/lp/lp-media@2x.webp';
import technology from '../assets/lp/lp-technology.webp';
import technology2x from '../assets/lp/lp-technology@2x.webp';
import regions from '../assets/lp/lp-regions.webp';
import regions2x from '../assets/lp/lp-regions@2x.webp';
import kochi from '../assets/lp/lp-kochi.webp';
import kochi2x from '../assets/lp/lp-kochi@2x.webp';

import londonLdm from '../assets/London/Ldm.png';
import londonLsd from '../assets/London/Lsd.png';
import londonLseo from '../assets/London/Lseo.png';
import londonLwd from '../assets/London/Lwd.png';

const IMAGES = {
  marketing: {
    src: marketing,
    srcSet: `${marketing} 640w, ${marketing2x} 1120w`,
    alt: 'Infynix marketing dashboards and campaign reporting on a desk setup',
  },
  media: {
    src: media,
    srcSet: `${media} 640w, ${media2x} 1120w`,
    alt: 'Content production desk with camera, ring light and video editing timeline',
  },
  technology: {
    src: technology,
    srcSet: `${technology} 640w, ${technology2x} 1120w`,
    alt: 'Connected devices and systems visualised as a single linked platform',
  },
  regions: {
    src: regions,
    srcSet: `${regions} 640w, ${regions2x} 1120w`,
    alt: 'Laptop showing a map of the regions Infynix Solutions delivers into',
  },
  // This is Oberon Mall, Padivattom, which is where the Infynix office
  // actually is (3rd floor). The alt text can say so.
  kochi: {
    src: kochi,
    srcSet: `${kochi} 640w, ${kochi2x} 1120w`,
    alt: 'Oberon Mall, Padivattom, Edappally, home to the Infynix Solutions office in Kochi',
  },
  londonDm: {
    src: londonLdm,
    srcSet: `${londonLdm} 640w`,
    alt: 'Digital Marketing Agency in London',
  },
  londonSd: {
    src: londonLsd,
    srcSet: `${londonLsd} 640w`,
    alt: 'Software Development Company in London',
  },
  londonSeo: {
    src: londonLseo,
    srcSet: `${londonLseo} 640w`,
    alt: 'SEO Company in London',
  },
  londonWd: {
    src: londonLwd,
    srcSet: `${londonLwd} 640w`,
    alt: 'Web Design Company in London',
  },
};

/** Lead image for the page hero, chosen from what the page is actually about. */
export const heroImageFor = (page) => {
  if (!page) return IMAGES.marketing;

  if (page.heroImage && IMAGES[page.heroImage]) {
    return IMAGES[page.heroImage];
  }

  if (page.city === 'London' || (page.slug && page.slug.includes('london'))) {
    if (page.slug === 'seo-company-in-london' || /seo/i.test(page.service)) {
      return IMAGES.londonSeo;
    }
    if (page.slug === 'digital-marketing-agency-in-london' || /digital marketing/i.test(page.service)) {
      return IMAGES.londonDm;
    }
    if (page.slug === 'web-design-company-in-london' || /web design/i.test(page.service) || /ui-ux/i.test(page.slug)) {
      return IMAGES.londonWd;
    }
    if (page.slug === 'software-development-company-in-london' || /software|mobile|ecommerce/i.test(page.service)) {
      return IMAGES.londonSd;
    }
  }

  if (/social|media/i.test(page.service)) return IMAGES.media;
  return page.category === 'technology' ? IMAGES.technology : IMAGES.marketing;
};

/** Supporting image for the "why this place" section. */
export const localImageFor = (page) =>
  page.city === 'Kochi' ? IMAGES.kochi : IMAGES.regions;

export default IMAGES;
